/**
 * Plugin template for the Ralph write-guardrail plugin.
 * Extracted from init.ts for better code organization.
 */

/**
 * Marker for generated plugin files.
 * This marker indicates the file was created by `ralph init` and is safe to remove with `ralph --reset`.
 */
export const GENERATED_PLUGIN_MARKER = `// Generated by ralph init
// generator: ralph-init
// safe_to_delete: true
`;

/**
 * Check if a plugin file was generated by ralph init.
 */
export function isGeneratedPlugin(content: string): boolean {
  return content.startsWith("// Generated by ralph init");
}

/**
 * Template for the write-guardrail plugin.
 * This plugin protects specified files from being overwritten or modified by AI agents.
 */
export const PLUGIN_TEMPLATE = `${GENERATED_PLUGIN_MARKER}
import type { Plugin } from "@opencode-ai/plugin"

/**
 * Ralph Write Guardrail Plugin
 * 
 * Protects user-configurable files from being overwritten or deleted by:
 * - Write tool: Blocks full file overwrites
 * - Bash tool: Blocks commands that overwrite/delete protected files
 * 
 * NOTE: Edit tool is NOT blocked. Agents should use surgical edits (Edit tool)
 * instead of destructive operations. This is intentional by design.
 * 
 * Protected files by default:
 * - prd.json - The PRD plan file
 * - progress.txt - Progress tracking
 * - .ralph-prompt.md - Prompt template
 * - AGENTS.md - Agent configuration
 * 
 * To customize, modify the PROTECTED_FILES array below.
 */

// Files that should be protected from AI modification
const PROTECTED_FILES = [
  "prd.json",
  "progress.txt",
  ".ralph-prompt.md",
  "AGENTS.md",
]

// Patterns for destructive bash commands targeting files
const DESTRUCTIVE_COMMAND_PATTERNS = [
  // rm commands
  /^rm\\s+.*\\b(FILENAME)\\b/,
  /^rm\\s+-[rf]+\\s+.*\\b(FILENAME)\\b/,
  // mv commands (moving/renaming protected files)
  /^mv\\s+.*\\b(FILENAME)\\b/,
  // cp overwriting protected files (cp source dest where dest is protected)
  /^cp\\s+.*\\s+(FILENAME)\\s*$/,
  // Redirect operators that would overwrite
  /[>|]\\s*(FILENAME)\\b/,
  // truncate command
  /^truncate\\s+.*\\b(FILENAME)\\b/,
  // shred command
  /^shred\\s+.*\\b(FILENAME)\\b/,
]

/**
 * Checks if a file path matches any protected file.
 * Handles both absolute and relative paths.
 */
function isProtectedFile(filePath: string): string | null {
  const normalizedPath = filePath.replace(/\\\\/g, "/")
  for (const protectedFile of PROTECTED_FILES) {
    if (
      normalizedPath === protectedFile ||
      normalizedPath.endsWith("/" + protectedFile) ||
      normalizedPath.endsWith("\\\\" + protectedFile)
    ) {
      return protectedFile
    }
  }
  return null
}

/**
 * Checks if a bash command would modify any protected file.
 */
function wouldModifyProtectedFile(command: string): string | null {
  for (const protectedFile of PROTECTED_FILES) {
    // Create file-specific patterns
    const escapedFileName = protectedFile.replace(/[.*+?^\${}()|[\\]\\\\]/g, "\\\\$&")
    
    for (const patternTemplate of DESTRUCTIVE_COMMAND_PATTERNS) {
      const pattern = new RegExp(
        patternTemplate.source.replace(/FILENAME/g, escapedFileName),
        patternTemplate.flags
      )
      if (pattern.test(command)) {
        return protectedFile
      }
    }
    
    // Also check for simple string presence with destructive keywords
    if (command.includes(protectedFile)) {
      const dangerousKeywords = ["rm ", "rm\\t", "mv ", "truncate ", "shred ", "> ", ">> "]
      for (const keyword of dangerousKeywords) {
        if (command.includes(keyword)) {
          return protectedFile
        }
      }
    }
  }
  return null
}

export const RalphWriteGuardrail: Plugin = async () => {
  return {
    "tool.execute.before": async (input, output) => {
      // Guard against write tool (full file overwrites)
      // Note: Edit tool is NOT blocked - surgical edits are the preferred approach
      if (input.tool === "write") {
        const filePath = output.args?.filePath as string | undefined
        if (filePath) {
          const protectedFile = isProtectedFile(filePath)
          if (protectedFile) {
            throw new Error(
              \`[Ralph Guardrail] Cannot overwrite protected file: \${protectedFile}. \\n\` +
              \`This file is managed by Ralph and should not be modified directly by AI. \\n\` +
              \`Use the Edit tool for surgical changes instead.\`
            )
          }
        }
      }

      // Guard against bash commands that could modify protected files
      if (input.tool === "bash") {
        const command = output.args?.command as string | undefined
        if (command) {
          const protectedFile = wouldModifyProtectedFile(command)
          if (protectedFile) {
            throw new Error(
              \`[Ralph Guardrail] Bash command would modify protected file: \${protectedFile}. \\n\` +
              \`Command: \${command}\\n\` +
              \`This file is managed by Ralph and should not be modified by shell commands.\`
            )
          }
        }
      }
    },
  }
}
`;
